CREATE OR REPLACE FUNCTION public.comparePlpgsql(input INTEGER) RETURNS VARCHAR AS
$$
BEGIN
    RETURN (SELECT name FROM btreeindex WHERE id = input);
END;
$$ LANGUAGE PLPGSQL RETURNS NULL ON NULL INPUT;

DROP FUNCTION IF EXISTS comparesql;
CREATE FUNCTION comparesql(input INTEGER) RETURNS CHARACTER VARYING AS
$$
SELECT name
FROM btreeindex
WHERE id = input;
$$ LANGUAGE SQL;